// <auto-generated />
using System;
using InventarioProduto.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventarioProduto.Migrations
{
    [DbContext(typeof(InventarioProdutoDbContext))]
    partial class InventarioProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventarioProduto.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("_id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("_LastModifiedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedTime");

                    b.Property<DateTime>("_creationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.HasKey("_id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            _id = new Guid("e2a8c9f0-7d3b-4a1e-9c6a-08d7e5b4c3f2"),
                            Nome = "Produto A",
                            Preco = 29.98m,
                            Quantidade = 10,
                            _creationTime = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            _id = new Guid("b5d9e8c1-6a2f-4b0d-8a3e-1f9c8b7a6d5e"),
                            Nome = "Produto B",
                            Preco = 59.98m,
                            Quantidade = 4,
                            _creationTime = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            _id = new Guid("c9f0b7a2-5e1d-4c9a-b2d8-2a0e1c9f8b7d"),
                            Nome = "Produto C",
                            Preco = 109.98m,
                            Quantidade = 2,
                            _creationTime = new DateTime(2025, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
